### PR TITLE
dynamic text for twitter embed

### PR DESCRIPTION
**Pull request by akshajb**
Added dynamic text for twitter share on each section.

### CODE REVIEW

**Comment by encody** [comment]
@akshajb Oh, do you have the [server](https://github.com/NEAR-Edu/stats.gallery-server) set up on your local?

**Comment by akshajb** [comment]
@encody I am using WSL as my dev env and have postgres installed. I was not able to import the sql dump though. I might need some help to get the server set up.

**Comment by akshajb** [comment]
When I try to import the file into the database that I created I get the following error. 
image

**Comment by encody** [comment]
Oops, I ran the export with incorrect settings. I'll get that fixed soon, although I am not able to right now. Thanks for pointing this out.

**Comment by encody** [comment]
Closing for inactivity.

**Pull request closed without merging**
